version: '2'
services:
  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '5000:5000'

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '9632:9632'
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./server/public/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules
    restart: on-failure

  mongo-dev:
    image: mongo:3.6
    #     environment:
    #      - MONGO_INITDB_ROOT_USERNAME=mongo
    #      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'

  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - '5432:5432'
    restart: on-failure

volumes:
  server-dev:
